train_file:  '../Data/re_data/coco_train.json'
val_file: '../Data/re_data/coco_val.json'                
test_file: '../Data/re_data/coco_test.json'
image_root: '../Data/images'

batch_size_train: 1024
batch_size_test: 256
k_test: 128

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warm_up: False, warmup_lr: 1e-6, warmup_epochs: 1, cooldown_epochs: 0}

# Evaluation Metrics
metrics: ['i2t_r1', 't2i_r1', 'r_mean']
